name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

env:
  # Ajuste para o caminho da pasta onde existem pubspec.yaml e lib/main.dart
  APP_DIR: ./POSTO   # exemplo: ./app  ou  ./posto

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build for GitHub Pages
        run: |
          flutter build web --release \
            --base-href /POSTO/

      - name: SPA 404 fallback
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publica a pasta de build localizada *dentro* do APP_DIR
          publish_dir: ${{ env.APP_DIR }}/build/web